name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v5

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
        with:
          # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: 3.12 # optional

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel[uv]

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        env:
          CIBW_BEFORE_ALL_WINDOWS: bash install_cuda.sh
          CIBW_BEFORE_BUILD_WINDOWS: uv pip install "torch>=2.3.0+cu128" "triton-windows>=3.0.0" --torch-backend=cu128
          CIBW_BUILD_FRONTEND: "build[uv]; args: --no-isolation"
        #   ...

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
